package app.mango.music.manager

object Config {

    const val LAST_PLAYED_SP = "LAST_PLAYED_SP"
    const val LAST_PLAYED_ID = "LAST_PLAYED_ID"
    const val LAST_PLAYED_LIST = "LAST_PLAYED_LIST"

    const val KEY_SETTINGS_MEDIA_UNKNOWN_FILTER = "KEY_SETTINGS_MEDIA_UNKNOWN_FILTER"
    const val KEY_SETTINGS_IGNORE_AUDIO_FOCUS = "KEY_SETTINGS_IGNORE_AUDIO_FOCUS"
    const val KEY_SETTINGS_REPEAT_MODE = "KEY_SETTINGS_REPEAT_MODE"
    const val KEY_SETTINGS_PLAYBACK_PARAMETERS = "KEY_SETTINGS_PLAYBACK_PARAMETERS"
    const val KEY_SETTINGS_VOLUME = "KEY_SETTINGS_VOLUME"
    const val KEY_SETTINGS_AUDIO_EFFECT = "KEY_SETTINGS_AUDIO_EFFECT"
    const val KEY_SETTINGS_AUDIO_EFFECT_VALUE = "KEY_SETTINGS_AUDIO_EFFECT_VALUE"
    const val KEY_SETTINGS_AUDIO_EFFECT_BOOST = "KEY_SETTINGS_AUDIO_EFFECT_BOOST"
    const val KEY_SETTINGS_AUDIO_EFFECT_BOOST_VALUE = "KEY_SETTINGS_AUDIO_EFFECT_BOOST_VALUE"

    const val DEFAULT_SETTINGS_MEDIA_UNKNOWN_FILTER = true
    const val DEFAULT_SETTINGS_IGNORE_AUDIO_FOCUS = false
    const val DEFAULT_SETTINGS_REPEAT_MODE = 0
    const val DEFAULT_SETTINGS_PLAYBACK_PARAMETERS = "1"
    const val DEFAULT_SETTINGS_VOLUME = 100
    const val DEFAULT_SETTINGS_AUDIO_EFFECT = false
    const val DEFAULT_SETTINGS_AUDIO_EFFECT_BOOST = false
    const val DEFAULT_SETTINGS_AUDIO_EFFECT_BOOST_VALUE = 0
}